### ISSUE TITLE
Atom crash after narrow:search

### ISSUE THREAD

**Issue by kdnk** [t9md/atom-narrow#239]
When I search some word by `narrow:search` and I move cursor to bottom in `narrow-editor`, Atom always freeze up like following gif(only vim-mode-plus & atom-narrow is activated).

![kapture 2017-08-14 at 21 07 20](https://user-images.githubusercontent.com/15260226/29271064-9cfd040e-8134-11e7-8eeb-37fa34d720d3.gif)

I can't see console so this might not be caused by narrow.
Have you ever seen like this crash and do you know why this caused?

Thanks!

Atom: 1.19.0
vim-mode-plus: 0.96.2
atom-narrow: 0.50.3

**Comment by t9md** [comment]
I can't reproduce and haven't experienced that.

What your OS?

What is your narrow config?

Do you tune key-repeat rate via Karabiner or similar software?

In your GIF, why auto-preview is not happen while you are moving down, because of too fast or you explicitly disable it?

**Comment by kdnk** [comment]
I use macOS 10.12.6.

My narrow config is following.
```
  narrow:
    Search:
      autoPreview: false
      autoPreviewOnQueryChange: false
      revealOnStartCondition: "always"
    directionToOpen: "down:always-new-pane"
    queryCurrentWordByDoubleClick: false
```
I turn off auto-preview only for `narrow:search`.

I tune key-repeat rate via System Preferences, not using like Karabiner.
