### ISSUE TITLE
[Feature request] Better highlighting

### ISSUE THREAD

**Issue by sonhanguyen** [t9md/atom-narrow#256]
Is there a way to make syntax highlighting works with different languages in the result? The markdown grammar can use the annotation from the quoted code blocks to highlight them accordingly, so it should be doable.

It seems there are two ways to do this:
- Render the results as markdown and use the markdown grammar
- Figure out how markdown does it and add similar logic to the narrow grammar

Looking for some hacktoberfest contribution so I can give a hand

**Comment by slavaGanzin** [comment]
I think, it will be super slow or inaccurate. Or both.

**Comment by sonhanguyen** [comment]
fair enough, the main reason I wanted this is because there is no visual aid at all so it's hard to discern between elements of the result (is it just me or `git-diff-all` looks completely flat?). I think there are a few thing we can do to improve readability, like bolding the file name and draw lines separating matches.

**Comment by t9md** [comment]
Narrow used to use markdown-like suntax highlight using grammar rule in old days but changed to improve more controllability once atom support foreground font colort change via drcoration.

I could not get your original background, could you paste GIF to show 'flat color'?

**Comment by sonhanguyen** [comment]
![screen shot 2017-10-18 at 10 22 53 am](https://user-images.githubusercontent.com/13200207/31694161-6171b4ec-b3ee-11e7-86b2-8bb1fc063223.png)
The color scheme I'm using is `duotone-dark-sea`, notice I also narrow the narrow pane (no pun intended) like how I usually have it. The long path and lack of coloring makes it a bit hard to read.

**Comment by t9md** [comment]
You can change how header is displayed via setting of narrow(see GIF below).
Open setting-view then follow, `Package > Narrow` then find/modify `File Header Template` setting.

Default value might be too minimalistic when I consider this time situation, maybe I should revert default to old `# dir/to/file` style.

![settings_ ___github_atom-vim-mode-plus](https://user-images.githubusercontent.com/155205/31694425-351f14de-b3df-11e7-9b19-3d2217dc1eb9.jpg)

For highlight, I maybe can improve highlight by detecting base text syntax color.
For the time being, you can change it in your `init.less` custom style.

- init.less

here is exactly same as default narrow's highlight.
You can experiment based on it(e.g. make `.narrow-syntax--header-file` to `red`).

```less
atom-text-editor {
  .narrow-syntax--search-term {
    color: @syntax-color-function !important;
  }
  .narrow-syntax--include-filter {
    color: @syntax-color-keyword;
  }
  .narrow-syntax--exclude-filter {
    color: @syntax-color-removed;
  }
  .narrow-syntax--truncation-indicator {
    color: @syntax-color-removed;
  }
  .narrow-syntax--header-project {
    color: @syntax-color-snippet;
  }
  .narrow-syntax--header-file {
    color: @syntax-color-variable;
  }
}
```

**Comment by t9md** [comment]
this is example distinguishable with `duotone-dark-sea`.

```less
atom-text-editor {
  .narrow-syntax--header-project {
    color: @syntax-color-added;
  }
  .narrow-syntax--header-file {
    color: @syntax-color-modified;
  }
}
```
